android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.incremental=true
# ponytail: builds rapidos sin IDE, subir a 4g solo si tienes 16GB+ RAM
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.nonTransitiveRClass=true
